### PR TITLE
scipy.io.wavfile.read() does not read 1D numpy arrays

### PR DESCRIPTION
**Pull request by enviz**
The wav file that I was trying to convert returned a one dimensional numpy array and it was showing an error because a 1D numpy array does not show the number of rows as 1. 
Because of which on line 122: M, numChannels = data.shape  will show an error saying that it expected 2 arguments but it only got one. 

So this is a slight modification to the code. 
Thanks for the upload.

### CODE REVIEW

**Comment by michaeldzjap** [comment]
Yes, I see the problem. But your solution doesn't quite make sense to me. Why would you want to reshape a mono signal into a stereo signal?

I think a better solution (untested) would be to change the code to something like:

```python
SR, data = scipy.io.wavfile.read(args.ifile)
if data.ndim == 1:
    M, numChannels = data.size, 1
else:
    M, numChannels = data.shape
```

**Comment by enviz** [comment]
sure,it works. I just checked it.
But if it's a requirement that only mono files should be given as input,then please mention it in README.md

And also, just out of curiosity, will the .json file be affected drastically if the audio file changes its shape from mono to stereo?

**Comment by michaeldzjap** [comment]
> But if it's a requirement that only mono files should be given as input, then please mention it in README.md

No, this is not a requirement. In fact, you should be able to supply any number of channels with the existing code. But indeed, the current version doesn't handle mono .wav files correctly. This needs to be fixed. But your solution of doing this: `data = numpy.reshape(data, (-1, 2)) ` on a mono file (i.e. 1D array of samples) is not correct. Because you are splitting your original mono signal into two (e.g. [1, 2, 3, 4] becomes [[1, 2], [3, 4]]). That is why I proposed my version (please review this, it is not the same as your modified pull request).

I am happy to take a look at this myself either tomorrow or the day after and push a fix myself. I should have some time to do this.

**Comment by enviz** [comment]
> But indeed, the current version doesn't handle mono .wav files correctly.
This is why i tried to add data = numpy.reshape(data, (-1, 2))



> That is why I proposed my version (please review this, it is not the same as your modified pull request).
Alright. I'll cancel my request. Update the code as per your modification.

**Comment by michaeldzjap** [comment]
I've updated the code. Should work now for mono files. Note that you will need _Python_ 3 now.

**Pull request closed without merging**
